// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// AlleleProbExp
NumericMatrix AlleleProbExp(IntegerMatrix depth, NumericVector alleleProb);
RcppExport SEXP _polyRAD_AlleleProbExp(SEXP depthSEXP, SEXP alleleProbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alleleProb(alleleProbSEXP);
    rcpp_result_gen = Rcpp::wrap(AlleleProbExp(depth, alleleProb));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_polyRAD_AlleleProbExp", (DL_FUNC) &_polyRAD_AlleleProbExp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_polyRAD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
