# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BestGenos <- function(probs, ploidy, ntaxa, nalleles) {
    .Call('_polyRAD_BestGenos', PACKAGE = 'polyRAD', probs, ploidy, ntaxa, nalleles)
}

BestPloidies <- function(chisq) {
    .Call('_polyRAD_BestPloidies', PACKAGE = 'polyRAD', chisq)
}

ThirdDimProd <- function(probs, ngen, ntaxa) {
    .Call('_polyRAD_ThirdDimProd', PACKAGE = 'polyRAD', probs, ngen, ntaxa)
}

