# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AlleleProbExp <- function(depth, alleleProb) {
    .Call('_polyRAD_AlleleProbExp', PACKAGE = 'polyRAD', depth, alleleProb)
}

BestGenos <- function(probs, ploidy, ntaxa, nalleles) {
    .Call('_polyRAD_BestGenos', PACKAGE = 'polyRAD', probs, ploidy, ntaxa, nalleles)
}

BestPloidies <- function(chisq) {
    .Call('_polyRAD_BestPloidies', PACKAGE = 'polyRAD', chisq)
}

